#!/usr/bin/env zsh

### GIT ###
alias gips='git push'
alias gipl='git pull'
alias gis='git status'
alias gim='git commit -m'
alias gima='git commit --amend'
alias gico='git checkout'
alias gicob='git checkout -b'
alias gig='git log'
alias gia='git add'
alias gipa='git add -p'
alias gidf='git diff'
alias gidfe='git diff --cached'
alias gibra='git branch'
alias gimer='git merge'
alias gitsta='git stash'
alias cdo='[ $(git rev-parse --git-dir 2>& /dev/null) ] && cd `git rev-parse --show-toplevel`  || echo "Not in working git tree"'
alias clone='git clone'

### SYSTEM RUST TOOLS
alias ls=exa
alias l='exa -l -s size'
alias find=fd
alias grep=rg

### SYSTEM ###
alias getip='hostname -i'
alias vim='vim -X'
alias vi='vim -X'
alias t=task
alias cdd='cd `xdg-user-dir DOWNLOAD`'
alias cdi='cd `xdg-user-dir PICTURES`' 
alias cdm='cd `xdg-user-dir MUSIC`' 
alias cds='cd ~/code/Scriptazos'
alias cdb='cd ~/.local/bin'
alias fgrep='rg -F --color=auto'

### OTHER ###
alias tmux='tmux attach -t base || tmux new -s base'
alias dl-music='youtube-dl -x --audio-quality 0 --audio-format vorbis'
alias vip='vim +"Project .vimproject"'
