#!/usr/bin/env zsh
source $HOME/.zimfw.zsh

source $HOME/.functions

sourceBasicDotFiles
sourceBSCDotFiles
conda_setup


# Theme
#

fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure
