#!/usr/bin/env zsh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for file in $(ls -A basicDotFiles | grep "^\."); do ln -s $PWD/basicDotFiles/$file $HOME/$file; done

ln -s $DIR/systemd/ $HOME/.config/systemd
ln -s $DIR/oh-my-zsh/ $HOME/.oh-my-zsh
