#!/usr/bin/env zsh


createDotFilesSymLinks()
{
    for file in $(ls -d $1/.?*); do
        ln -snf  $( realpath $file) $HOME/$( basename $file)
    done
}


createBasicAndExtendedDotFilesSymLinks()
{
    createDotFilesSymLinks basicDotFiles 
    createDotFilesSymLinks extendedDotFiles/BSCDotFiles 
    ln -snf $( realpath oh-my-zsh/) $HOME/.oh-my-zsh
}
